# Generated by Django 4.2.2 on 2023-06-21 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_release', models.IntegerField(verbose_name='Год выпуска')),
                ('body_type', models.CharField(max_length=20, verbose_name='Тип кузова')),
                ('engine_capacity', models.IntegerField(verbose_name='Объем двигателя')),
                ('engine_power', models.IntegerField(verbose_name='Мощность двигателя')),
                ('drive', models.CharField(max_length=20, verbose_name='Привод')),
                ('fuel_consumption', models.IntegerField(verbose_name='Расход топлива')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество мест')),
                ('trunk_volume', models.IntegerField(verbose_name='Объем багажника')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.brands', verbose_name='Фирмы')),
                ('characteristics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.characteristics', verbose_name='Характеристики')),
            ],
        ),
    ]
