# Generated by Django 4.2.2 on 2023-06-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='shor_content',
            new_name='short_content',
        ),
    ]
