# Generated by Django 4.2.2 on 2023-07-15 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['time_publsihed'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='post',
            name='time_publsihed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['time_publsihed'], name='cars_post_time_pu_fe0b64_idx'),
        ),
    ]
