# Generated by Django 4.2.2 on 2023-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='likes_amount',
            field=models.IntegerField(null=True, verbose_name='Лайки'),
        ),
    ]
