# Generated by Django 4.2.2 on 2023-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/profile_picture/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
