# Generated by Django 4.2.2 on 2023-06-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_cars_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_release', models.IntegerField(verbose_name='Год выпуска')),
                ('body_type', models.CharField(max_length=20, verbose_name='Тип кузова')),
                ('engine_capacity', models.IntegerField(verbose_name='Объем двигателя')),
                ('engine_power', models.IntegerField(verbose_name='Мощность двигателя')),
                ('drive', models.CharField(max_length=20, verbose_name='Привод')),
                ('fuel_consumption', models.IntegerField(verbose_name='Расход топлива')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество мест')),
                ('trunk_volume', models.IntegerField(verbose_name='Объем багажника')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.characteristics'),
        ),
    ]
