# Generated by Django 4.2.2 on 2023-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_likes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='likes_amount',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
