# Generated by Django 4.2.2 on 2023-07-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_post_options_post_time_publsihed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['time_create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='cars_post_time_pu_fe0b64_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_publsihed',
        ),
    ]
