# Generated by Django 4.2.2 on 2023-06-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_characteristics_cars_characteristics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brands',
        ),
    ]
