# Generated by Django 4.2.2 on 2023-07-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_comment_slug_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_create', 'content'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
